server:
  port: 8082

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: producer-service
          uri: lb://kafka-producer-service
          predicates:
            - Path=/producer/**
        - id: consumer-service
          uri: lb://kafka-consumer-service
          predicates:
            - Path=/consumer/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
